# Generated by Django 5.2 on 2025-04-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AVIESTOR_APP', '0002_stockprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginfrom',
            name='username',
        ),
        migrations.AddField(
            model_name='loginfrom',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
