# Generated by Django 5.2 on 2025-04-16 10:00

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('AVIESTOR_APP', '0004_alter_registerform_phone_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=50, default=''),
        ),
    ]
