# Generated by Django 5.2 on 2025-04-16 10:00

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('AVIESTOR_APP', '0005_add_username_to_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
