# Generated by Django 5.2 on 2025-04-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AVIESTOR_APP', '0005_add_username_to_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registerform',
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
