# Generated by Django 5.2 on 2025-04-16 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AVIESTOR_APP', '0006_delete_registerform_alter_profile_username'),
        ('AVIESTOR_APP', '0006_remove_username_from_profile'),
    ]

    operations = [
    ]
